# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [4]:
# Your code here
import numpy as np
A = np.array([
   [1, 2, 3], 
   [4, 5, 6],
   [7, 8, 9]])

B = np.array([
   [11, 12, 13], 
   [14, 15, 16],
   [17, 18, 19]])

C = np.array([
   [21, 22, 23], 
   [24, 25, 26],
   [27, 28, 29]])

In [8]:
print(A.dot(B+C))
print(A.dot(B)+A.dot(C))
print(A.dot(B)+A.dot(C)==A.dot(B+C))

[[ 240  252  264]
 [ 582  612  642]
 [ 924  972 1020]]
[[ 240  252  264]
 [ 582  612  642]
 [ 924  972 1020]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [11]:
# Your code here 
print(A.dot(B.dot(C)))
print(A.dot(B).dot(C))
print(A.dot(B).dot(C)==A.dot(B.dot(C)))

[[ 6948  7236  7524]
 [16722 17415 18108]
 [26496 27594 28692]]
[[ 6948  7236  7524]
 [16722 17415 18108]
 [26496 27594 28692]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [12]:
# Your code here 
print(A.dot(B))
print(B.dot(A))
print(A.dot(B)==B.dot(A))


[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[150 186 222]
 [186 231 276]
 [222 276 330]]
[[False False False]
 [False  True False]
 [False False False]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [33]:
# Your code here 

# print(A.T.dot(B))
print(np.transpose(A).dot(B))
# print(B.T.dot(A))
print(np.transpose(B).dot(A))

print(A.T.dot(B) == B.T.dot(A))

[[186 198 210]
 [228 243 258]
 [270 288 306]]
[[186 228 270]
 [198 243 288]
 [210 258 306]]
[[ True False False]
 [False  True False]
 [False False  True]]


In [35]:
x = np.array([[2], [6], [7]])
y = np.array([[3], [5], [9]])

left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)
print(left, right)

[[99]] [[99]]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [31]:
# Your code here 
print(A.dot(B).T)
print(B.T.dot(A.T))

print(A.dot(B).T == B.T.dot(A.T))

[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]
[[ 90 216 342]
 [ 96 231 366]
 [102 246 390]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 